"""add_system_config_table

Revision ID: 59da0acbc792
Revises: 38caeed13de1
Create Date: 2026-06-20 11:17:30.411029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59da0acbc792'
down_revision: Union[str, None] = '38caeed13de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('default_language', sa.String(length=5), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('monthly_default_duration_days', sa.Integer(), nullable=False),
    sa.Column('monthly_expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('session_based_expiry_warning_sessions', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # Note: No seed row — GET /api/config returns FALLBACK_CONFIG when table is empty.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    # ### end Alembic commands ###
