"""enrollments_and_visitors

Revision ID: 8820c12c3ea8
Revises: 016_sprint4_alter
Create Date: 2026-08-01 14:06:00.190349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8820c12c3ea8'
down_revision: Union[str, None] = '016_sprint4_alter'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_enrollment_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('guardian_phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('converted_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['converted_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('system_config', sa.Column('enrollment_reservation_hold_hours', sa.Integer(), nullable=False, server_default='72'))
    
    # Fast capacity counting
    op.create_index(
        'idx_enrollments_group_status',
        'enrollments', ['group_id', 'status']
    )
    # Fast waitlist ordering per group
    op.create_index(
        'idx_enrollments_group_waitlist',
        'enrollments', ['group_id', 'waitlist_position'],
        postgresql_where=sa.text("status = 'waitlisted'")
    )
    # Fast "my enrollments" lookups
    op.create_index(
        'idx_enrollments_student_status',
        'enrollments', ['student_id', 'status']
    )
    # Duplicate-enrollment guard: student cannot hold 2 non-terminal enrollments in same group
    op.create_index(
        'idx_enrollments_no_duplicate_active',
        'enrollments', ['group_id', 'student_id'],
        unique=True,
        postgresql_where=sa.text(
            "student_id IS NOT NULL AND status IN ('pending', 'waitlisted', 'active')"
        )
    )
    # Visitor request indexes
    op.create_index('idx_visitor_requests_status', 'visitor_enrollment_requests', ['status'])
    op.create_index(
        'idx_visitor_requests_created',
        'visitor_enrollment_requests', ['created_at'],
        postgresql_ops={'created_at': 'DESC'}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visitor_requests_created', table_name='visitor_enrollment_requests')
    op.drop_index('idx_visitor_requests_status', table_name='visitor_enrollment_requests')
    op.drop_index('idx_enrollments_no_duplicate_active', table_name='enrollments')
    op.drop_index('idx_enrollments_student_status', table_name='enrollments')
    op.drop_index('idx_enrollments_group_waitlist', table_name='enrollments')
    op.drop_index('idx_enrollments_group_status', table_name='enrollments')
    op.drop_table('visitor_enrollment_requests')
    # ### end Alembic commands ###
