"""sprint_6_subscriptions_payments

Revision ID: 90460db1c243
Revises: 8820c12c3ea8
Create Date: 2026-08-04 21:07:50.573553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90460db1c243'
down_revision: Union[str, None] = '8820c12c3ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_classes_level_rank', table_name='classes')
    op.drop_index('idx_classes_status', table_name='classes')
    op.drop_index('idx_enrollments_group_status', table_name='enrollments')
    op.drop_index('idx_enrollments_group_waitlist', table_name='enrollments', postgresql_where="((status)::text = 'waitlisted'::text)")
    op.drop_index('idx_enrollments_no_duplicate_active', table_name='enrollments', postgresql_where="((student_id IS NOT NULL) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'waitlisted'::character varying, 'active'::character varying])::text[])))")
    op.drop_index('idx_enrollments_student_status', table_name='enrollments')
    op.drop_index('ix_enrollments_branch_id', table_name='enrollments')
    op.drop_index('idx_groups_status', table_name='groups')
    op.drop_index('idx_modules_active', table_name='modules')
    op.drop_index('idx_modules_category', table_name='modules')
    op.drop_index('idx_sessions_branch_date', table_name='sessions')
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.drop_index('idx_visitor_requests_created', table_name='visitor_enrollment_requests')
    op.drop_index('idx_visitor_requests_status', table_name='visitor_enrollment_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_visitor_requests_status', 'visitor_enrollment_requests', ['status'], unique=False)
    op.create_index('idx_visitor_requests_created', 'visitor_enrollment_requests', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.create_index('idx_sessions_branch_date', 'sessions', ['branch_id', 'session_date'], unique=False)
    op.create_index('idx_modules_category', 'modules', ['category'], unique=False)
    op.create_index('idx_modules_active', 'modules', ['is_active'], unique=False)
    op.create_index('idx_groups_status', 'groups', ['status'], unique=False)
    op.create_index('ix_enrollments_branch_id', 'enrollments', ['branch_id'], unique=False)
    op.create_index('idx_enrollments_student_status', 'enrollments', ['student_id', 'status'], unique=False)
    op.create_index('idx_enrollments_no_duplicate_active', 'enrollments', ['group_id', 'student_id'], unique=True, postgresql_where="((student_id IS NOT NULL) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'waitlisted'::character varying, 'active'::character varying])::text[])))")
    op.create_index('idx_enrollments_group_waitlist', 'enrollments', ['group_id', 'waitlist_position'], unique=False, postgresql_where="((status)::text = 'waitlisted'::text)")
    op.create_index('idx_enrollments_group_status', 'enrollments', ['group_id', 'status'], unique=False)
    op.create_index('idx_classes_status', 'classes', ['status'], unique=False)
    op.create_index('idx_classes_level_rank', 'classes', ['level_rank'], unique=False)
    # ### end Alembic commands ###
