"""add_session_generation_horizon_weeks_to_system_config

Revision ID: ce1a704826eb
Revises: 015_add_positions
Create Date: 2026-07-22 15:08:05.988179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1a704826eb'
down_revision: Union[str, None] = '015_add_positions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_enrollments_branch_id'), 'enrollments', ['branch_id'], unique=False)
    op.add_column(
        'system_config',
        sa.Column(
            'session_generation_horizon_weeks',
            sa.Integer(),
            nullable=False,
            server_default='8',
        ),
    )
    # Remove server_default — the application model handles the default going forward
    op.alter_column('system_config', 'session_generation_horizon_weeks', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_config', 'session_generation_horizon_weeks')
    op.drop_index(op.f('ix_enrollments_branch_id'), table_name='enrollments')
    # ### end Alembic commands ###
