services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: PSP_DB
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  postgres_data: