from enum import Enum


class ErrorCode(str, Enum):
    # ─── Auth ────────────────────────────────────────────────────────────────
    VALIDATION_ERROR = "VALIDATION_ERROR"
    WRONG_CURRENT_PASSWORD = "WRONG_CURRENT_PASSWORD"
    UNAUTHORIZED = "UNAUTHORIZED"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # ─── Authorization ───────────────────────────────────────────────────────
    FORBIDDEN = "FORBIDDEN"
    FORBIDDEN_BRANCH = "FORBIDDEN_BRANCH"

    # ─── Users ───────────────────────────────────────────────────────────────
    NOT_FOUND = "NOT_FOUND"
    EMAIL_OR_PHONE_TAKEN = "EMAIL_OR_PHONE_TAKEN"
    LINK_ALREADY_EXISTS = "LINK_ALREADY_EXISTS"
    USER_HAS_ACTIVE_DEPENDENCIES = "USER_HAS_ACTIVE_DEPENDENCIES"
    CANNOT_DELETE_SELF = "CANNOT_DELETE_SELF"
    CANNOT_DELETE_LAST_OWNER = "CANNOT_DELETE_LAST_OWNER"
    PARENT_REQUIRES_STUDENT = "PARENT_REQUIRES_STUDENT"
    ADMIN_REQUIRES_BRANCH = "ADMIN_REQUIRES_BRANCH"

    # ─── Enrollments ─────────────────────────────────────────────────────────
    ALREADY_ENROLLED = "ALREADY_ENROLLED"
    GROUP_FULL = "GROUP_FULL"
    NOT_LINKED_CHILD = "NOT_LINKED_CHILD"
    VISITOR_REQUEST_ALREADY_RESOLVED = "VISITOR_REQUEST_ALREADY_RESOLVED"
    PARENT_ACTION_REQUIRED = "PARENT_ACTION_REQUIRED"
    CANNOT_CANCEL_ACTIVE_WITH_SUBSCRIPTION = "CANNOT_CANCEL_ACTIVE_WITH_SUBSCRIPTION"


    # ─── Rate Limiting ───────────────────────────────────────────────────────
    RATE_LIMITED = "RATE_LIMITED"

    # ─── Branches ────────────────────────────────────────────────────────────
    BRANCH_NAME_TAKEN = "BRANCH_NAME_TAKEN"
    BRANCH_HAS_ACTIVE_DEPENDENCIES = "BRANCH_HAS_ACTIVE_DEPENDENCIES"
    TOO_MANY_PHOTOS = "TOO_MANY_PHOTOS"
    INVALID_MAP_URL = "INVALID_MAP_URL"

    # ─── Config ──────────────────────────────────────────────────────────────
    CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND"

    # ─── Landing ─────────────────────────────────────────────────────────────
    LANDING_ABOUT_SINGLE_ITEM = "LANDING_ABOUT_SINGLE_ITEM"

    # ─── Academic ────────────────────────────────────────────────────────────
    MODULE_NAME_TAKEN = "MODULE_NAME_TAKEN"
    MODULE_HAS_ACTIVE_DEPENDENCIES = "MODULE_HAS_ACTIVE_DEPENDENCIES"
    CLASS_HAS_ACTIVE_DEPENDENCIES = "CLASS_HAS_ACTIVE_DEPENDENCIES"
    INVALID_LEVEL_TARGETING = "INVALID_LEVEL_TARGETING"
    TEACHER_NOT_ASSIGNED_TO_BRANCH = "TEACHER_NOT_ASSIGNED_TO_BRANCH"
    GROUP_HAS_ACTIVE_DEPENDENCIES = "GROUP_HAS_ACTIVE_DEPENDENCIES"
    INVALID_SCHEDULE_FORMAT = "INVALID_SCHEDULE_FORMAT"
    CANNOT_CHANGE_SUBSCRIPTION_TYPE = "CANNOT_CHANGE_SUBSCRIPTION_TYPE"
    ATTENDANCE_ALREADY_MARKED = "ATTENDANCE_ALREADY_MARKED"

    # ─── Subscriptions & Payments ────────────────────────────────────────────
    ENROLLMENT_NOT_PENDING = "ENROLLMENT_NOT_PENDING"
    SUBSCRIPTION_ALREADY_CANCELLED = "SUBSCRIPTION_ALREADY_CANCELLED"
    INVALID_EXTENSION_TARGET = "INVALID_EXTENSION_TARGET"
    INVALID_EXTENSION_AMOUNT = "INVALID_EXTENSION_AMOUNT"
    NO_ACTIVE_SUBSCRIPTIONS_TO_EXTEND = "NO_ACTIVE_SUBSCRIPTIONS_TO_EXTEND"
    AMOUNT_MUST_BE_POSITIVE = "AMOUNT_MUST_BE_POSITIVE"

    # ─── Attendance & Reschedule ─────────────────────────────────────────────
    ATTENDANCE_SESSION_NOT_MARKABLE = "ATTENDANCE_SESSION_NOT_MARKABLE"
    CANNOT_MARK_PRESENT_SUBSCRIPTION_EXPIRED = "CANNOT_MARK_PRESENT_SUBSCRIPTION_EXPIRED"
    RESCHEDULE_TARGET_INVALID = "RESCHEDULE_TARGET_INVALID"
    SESSION_NOT_RESCHEDULABLE = "SESSION_NOT_RESCHEDULABLE"
    RESCHEDULE_REQUEST_ALREADY_PENDING = "RESCHEDULE_REQUEST_ALREADY_PENDING"
    RESCHEDULE_REQUEST_ALREADY_RESOLVED = "RESCHEDULE_REQUEST_ALREADY_RESOLVED"
    SESSION_STATUS_INVALID_FOR_ACTION = "SESSION_STATUS_INVALID_FOR_ACTION"

    # ─── Server ──────────────────────────────────────────────────────────────
    INTERNAL_ERROR = "INTERNAL_ERROR"
